version: '3.8'

services:
  web:
    container_name: api_web
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
